In [3]:
import numpy
print(numpy.__version__)

1.26.4


In [12]:
import numpy as np

In [13]:
a = np.array
print(a)

<built-in function array>


In [14]:
 a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [15]:
a =  np.array([[1,2,3],[4,5,6]])
print(a)
print(a.dtype)
print(a.ndim)

[[1 2 3]
 [4 5 6]]
int32
2


In [16]:
a = np.array([1,2,3], complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [19]:
a = np.array([[1,2,3,4,5]])
print(a.size)
print(a.shape)

5
(1, 5)


In [4]:
import numpy as np

In [9]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Original')
print(a)
print(a.shape)

b = a.reshape(2,3)
print('Reshaped array')
print(b)

Original
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


ValueError: cannot reshape array of size 9 into shape (2,3)

In [12]:
# SLICING

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

print(a[0,1])
print(a[2,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
8


In [17]:
 a= np.array([1,2,3,5,56,57,687,945452])
print(a)
print("maximum number:", a.max())
print("minimum number:", a.min())
print("sum of all values:", a.sum())

[     1      2      3      5     56     57    687 945452]
maximum number: 945452
minimum number: 1
sum of all values: 946263


In [20]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
a = np.array([[1,2], [2,3],[4,5]])
print(a)

[[1 2]
 [2 3]
 [4 5]]


In [28]:
a = np.array([[1,2], [2,3],[4,5]])
print(a)
print("maximum number in columns:",  a.max(axis=0))
print("maximum number in rows:",  a.min(axis=1))
print(" sum of all values:",  a.sum(axis=1))

[[1 2]
 [2 3]
 [4 5]]
maximum number in columns: [4 5]
maximum number in rows: [1 2 4]
 sum of all values: [3 5 9]


In [30]:
# randn-------> generates  random number between (-1,0,1)

a= np.random.randn(3,4)
print(a)

[[-1.92371391 -1.65289002 -1.21916786 -1.57196203]
 [-0.82339687  0.20363164  0.7475774   0.20362515]
 [ 0.93195196  0.9204541  -0.63216321  0.98483733]]


In [34]:
import numpy as np

In [41]:
# arithmetic  operations

a = np.array([[1,2,3],[5,6,7]])
b = np.array([[2,3,5],[4,5,6]])

print("sum of a and b:\n",a+b)

sum of a and b:
 [[ 3  5  8]
 [ 9 11 13]]


In [ ]:
# RANGING FUNCTION-------> range()
# ranging function in numpy--------> arrange()

In [2]:
for i in range(11):
    print(i)

0
1
2
3
4
5
6
7
8
9
10


In [5]:
import numpy as np

In [6]:
print(np.array(11))

NameError: name 'np' is not defined

In [48]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
a = np.arange(12).reshape(2,2,3)
print(a)
print('***********************')
print(a[0])
print('***********************')
print(a[0][1])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
***********************
[[0 1 2]
 [3 4 5]]
***********************
[3 4 5]


In [9]:
import numpy as np

In [47]:
print(np.arange(12))
print(np.arage(12)[1:6])
print(np.arange(12)[1:5][1])

[ 0  1  2  3  4  5  6  7  8  9 10 11]


AttributeError: module 'numpy' has no attribute 'arage'

In [ ]:
# numpy broad casting

In [15]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([3,5,8,9,65,3,5])
c = a*b
print(c)

[  3  10  24  36 325  18  35]


In [22]:
a = np.array([[1,2,4,5],[2,4,5,6],[10,2,60,40]])
b = np.array([2,4,6,8])
print(a)
print('********************')
print(a+b)
print('**********************')
print(a-b)
print('**********************')
print(a*b)
print('**********************')
print(a/b)

[[ 1  2  4  5]
 [ 2  4  5  6]
 [10  2 60 40]]
********************
[[ 3  6 10 13]
 [ 4  8 11 14]
 [12  6 66 48]]
**********************
[[-1 -2 -2 -3]
 [ 0  0 -1 -2]
 [ 8 -2 54 32]]
**********************
[[  2   8  24  40]
 [  4  16  30  48]
 [ 20   8 360 320]]
**********************
[[ 0.5         0.5         0.66666667  0.625     ]
 [ 1.          1.          0.83333333  0.75      ]
 [ 5.          0.5        10.          5.        ]]


In [25]:
import numpy as np

In [46]:
a = np.arange(15).reshape(5,3)
print(a)
b= np.arange(5).reshape(5,3)
print(a+b)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


ValueError: cannot reshape array of size 5 into shape (5,3)

In [31]:
a = np.array([[1,2,3,4],[3,3,4,5],[23,2,35,5]])
print(a)
print('****************')
b = a.T
print(b)

[[ 1  2  3  4]
 [ 3  3  4  5]
 [23  2 35  5]]
****************
[[ 1  3 23]
 [ 2  3  2]
 [ 3  4 35]
 [ 4  5  5]]


In [39]:
print(np.array(['apple','banana','mango']))
print('*************')
print(np.array([['welcome'],['hi']]))
      

['apple' 'banana' 'mango']
*************
[['welcome']
 ['hi']]


In [43]:
print(np.char.add(['welcome'],['hi']))

['welcomehi']


In [45]:
a = np.array(['A','B'])
b = np.char.multiply(a,3)
print(b)

['AAA' 'BBB']


In [ ]:
# Rounding function

In [58]:
a = np.array([12.12,90.12,12.544,52.34])
print(a)
print('Round Function:', np.around(a))
print('Floor Function:', np.floor(a))
print('Ceil Function:', np.ceil(a))


[12.12  90.12  12.544 52.34 ]
Round Function: [12. 90. 13. 52.]
Floor Function: [12. 90. 12. 52.]
Ceil Function: [13. 91. 13. 53.]


In [69]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print('************************')
print(np.median(a))
print('************************')
print(np.mean(a))
print('************************')
print(np.median(a,0))# columns
print('************************')
print(np.median(a,1))# rows
print('************************')
print(np.average(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
************************
5.0
************************
5.0
************************
[4. 5. 6.]
************************
[2. 5. 8.]
************************
5.0


In [72]:
a = np.array([[100,200],[30,40]])
b = np.array([[10,20],[50,60]])
print(a)
print('*******************')
print(b)
print('********************')
print('Dot product of a and b')
print(np.dot(a,b))

[[100 200]
 [ 30  40]]
*******************
[[10 20]
 [50 60]]
********************
Dot product of a and b
[[11000 14000]
 [ 2300  3000]]
